debug: False
seed: 0
tag: ${now:%Y-%m-%d-%H-%M-%S}
upload_to_wandb: 1
original_cwd: ""
train: 1
do_pr_curve: 1
sample_complexity_test: 0
feature_type: dists_and_actions_only
#dataset_file_cache: /home/lagrassa/git/plan-abstractions/data/dataset_data.npy #helpful for sim models

data_aug:
  num_noise_aug : 3000
  num_grid_aug : 0
  state_noise_mag: 0.04
  action_noise_mag: 0.1 #0.05 worked well before

test_size: 0.05

shared_info:
  c1: 3
  c2: 1
  env:
    FrankaDrawerEnv
  sem_state_obj_names:
    - franka:ee
    - rod0
    - rod1
    - drawer
  train_cfg:
    lr: 0.002 #0.005 worked well
    max_epochs: 100
    N: 32
    batch_size: 128
    weight_decay: 1e-4 #0.005 worked well



precision_save_dir : /home/lagrassa/git/plan-abstractions/data/pr_curves
deviation_cfg:
  env: FrankaDrawerEnv
  type: MLPModel  #GPRModel #RFRModel #KNNRegressorModel #MLPModel #LinearRegressionModel #KNNRegressorModel
  run_path: iam-lab/asm/runs/uxqdgp99 #ew19rwqw  #33efv9w1 #71rzfuhs #3opju4wq #ew19rwqw    #3op601kz
  cache_dir: /home/lagrassa/plan_abstractions/cache
  acceptable_deviation: 0.05 #0.08
  c1: 5
  c2: 1
  sem_state_obj_names:
    - franka:ee
    - rod0
    - rod1
    - drawer
defaults:
  - envs: franka_env_drawer.yaml

wandb:
  init:
    entity: iam-lab
    project: sem
    group: alex/validation
  saver:
    upload: True

skills:
  LiftAndDrop:
    use_sim_model: False
    low_level: False
    env: FrankaDrawerEnv # PushRodEnv, FrankaDrawerEnv
    data:
      mock: False
      #root: /home/jacky/plan_abstractions/skill_data/LQRWaypointsXYZYawFranka
      #val_root: /home/jacky/plan_abstractions/skill_data/LQRWaypointsXYZYawFranka
      root: /home/lagrassa/git/plan-abstractions/data/iterative_drawer/iterative_training/skills/LiftAndDrop
      val_root: /home/lagrassa/git/plan-abstractions/data/iterative_drawer/iterative_training/skills/LiftAndDrop
      val_tags:
        - default__n_iter_0__seed_0
        - default__n_iter_0__seed_1
        - default__n_iter_0__seed_2
        - default__n_iter_0__seed_3
        - default__n_iter_0__seed_4
        - default__n_iter_0__seed_5
        - datacollect__n_iter_0__seed_0
        - datacollect__n_iter_0__seed_2
        - datacollect__n_iter_0__seed_3
      tags:
        - default__n_iter_0__seed_6
        - default__n_iter_0__seed_7
        - default__n_iter_0__seed_8
        - default__n_iter_0__seed_9
        - datacollect__n_iter_0__seed_4
        - datacollect__n_iter_0__seed_5
        - datacollect__n_iter_0__seed_6
      sem_state_obj_names:
        - franka:ee
        - rod0
        - rod1
        - drawer
      normalization_type: 'z_normalization'    # 'none', 'z_normalization', 'min_max'? #TODO use same as dynamics model
      z_normalization:
        # mean_std per feature ()
        # can only normalize values we require also maybe try min-max?
        mean: [  0,  0,  0,  0,  0,  0,  0,  0,  0,0,0,0,  828.628,   3.886,   0.059]
        std:  [  1,  1,  1,  1,  1,  1,  1,  1,  1,1,1,1,   22.012,   3.440,   0.004]
      skill: LiftAndDrop # the skill class name
      state_info:
        use_state_diff_in_end_state: True
        # anchor_obj_name: pusher # uncomment to use relative states
    sem_cfg:
      type: SEMAnalyticalDrawerAndRobot # SEMMLP
      env: FrankaDrawerEnv
      drawer_edge_dims : [0.25, 0.01, 0.07] #Make sure matches with URDF
      cache_dir: /home/lagrassa/plan_abstractions/cache
      run_path: iam-lab/asm/1us7b68u
      checkpoint: checkpoints/last.ckpt
      dim_state: 16
      predict:
        num_samples: 1
        truncate: 0.1

  Pick:
    use_sim_model: False
    low_level: False
    env: FrankaDrawerEnv # PushRodEnv, FrankaDrawerEnv
    data:
      mock: False
      #root: /home/jacky/plan_abstractions/skill_data/LQRWaypointsXYZYawFranka
      #val_root: /home/jacky/plan_abstractions/skill_data/LQRWaypointsXYZYawFranka
      root: /home/lagrassa/git/plan-abstractions/data/iterative_drawer/iterative_training/skills/Pick/
      val_root: /home/lagrassa/git/plan-abstractions/data/iterative_drawer/iterative_training/skills/Pick/
      val_tags:
        - default__n_iter_0__seed_0
        - default__n_iter_0__seed_1
        - default__n_iter_0__seed_2
        - default__n_iter_0__seed_3
        - default__n_iter_0__seed_4
        - default__n_iter_0__seed_5
        - datacollect__n_iter_0__seed_0
        - datacollect__n_iter_0__seed_2
        - datacollect__n_iter_0__seed_3
      tags:
        - default__n_iter_0__seed_6
        - default__n_iter_0__seed_7
        - default__n_iter_0__seed_8
        - default__n_iter_0__seed_9
        - datacollect__n_iter_0__seed_4
        - datacollect__n_iter_0__seed_5
        - datacollect__n_iter_0__seed_6
      sem_state_obj_names:
        - franka:ee
        - rod0
        - rod1
        - drawer
      normalization_type: 'z_normalization'    # 'none', 'z_normalization', 'min_max'? #TODO use same as dynamics model
      z_normalization:
        # mean_std per feature ()
        # can only normalize values we require also maybe try min-max?
        mean: [  0,  0,  0,  0,  0,  0,  0,  0,  0,0,0,0,  828.628,   3.886,   0.059]
        std:  [  1,  1,  1,  1,  1,  1,  1,  1,  1,1,1,1,   22.012,   3.440,   0.004]
      skill: LiftAndDrop # the skill class name
      state_info:
        use_state_diff_in_end_state: True
        # anchor_obj_name: pusher # uncomment to use relative states
    sem_cfg:
      type: SEMAnalyticalDrawerAndRobot # SEMMLP
      env: FrankaDrawerEnv
      drawer_edge_dims : [0.25, 0.01, 0.07] #Make sure matches with URDF
      cache_dir: /home/lagrassa/plan_abstractions/cache
      run_path: iam-lab/asm/1us7b68u
      checkpoint: checkpoints/last.ckpt
      dim_state: 16
      predict:
        num_samples: 1
        truncate: 0.1

