debug: False
seed: 0
tag: ${now:%Y-%m-%d-%H-%M-%S}
upload_to_wandb: 1
original_cwd: ""
train: 0
do_pr_curve: 0
sample_complexity_test: 0
feature_type: dists_and_actions_only
mde_stats_path: /home/lagrassa/git/plan-abstractions/data/mde_stats_final
#dataset_save_loc: /home/lagrassa/git/plan-abstractions/data/dataset_data_liftanddrop_sim_box_env.npy #helpful for sim models
dataset_file_cache: /home/lagrassa/git/plan-abstractions/data/dataset_data_liftanddrop_sim_box_env.npy #helpful for sim models

data_aug:
  num_noise_aug : 4000
  num_grid_aug : 0
  state_noise_mag: 0.008 #0.003
  action_noise_mag: 0.07 #0.05 worked well before

test_size: 0.05

shared_info:
  c1: 3
  c2: 1
  env:
    FrankaRodEnv
  use_sim_model: True
  sem_state_obj_names:
    - franka:ee
    - rod0
    - rod1
  train_cfg:
    lr: 0.0001 #0.005 worked well
    max_epochs: 50
    N: 64
    batch_size: 128
    weight_decay: 1e-6 #5e-3 #0.005 worked well
  sem_cfg:
    type: SEMAnalyticalDrawerAndRobot #SEMAnalyticalRodsAndRobot # SEMMLP
    env: FrankaRodEnv
    drawer_edge_dims : [0.25, 0.01, 0.07] #Make sure matches with URDF
    predict:
      num_samples: 1
      truncate: 0.1
    sem_state_obj_names:
      - franka:ee
      - rod0
      - rod1



precision_save_dir : /home/lagrassa/git/plan-abstractions/data/pr_curves
deviation_cfg:
  env: FrankaRodEnv
  type: MLPModel  #GPRModel #RFRModel #KNNRegressorModel #MLPModel #LinearRegressionModel #KNNRegressorModel
  #run_path: lagrassa/mdes/runs/3u8zgsxf
  run_path: iam-lab/asm/runs/3dov61e6
  cache_dir: /home/lagrassa/plan_abstractions/cache
  acceptable_deviation: 0.05 #0.08
  c1: 3
  c2: 1
  sem_state_obj_names:
    - franka:ee
    - rod0
    - rod1
defaults:
  - envs: franka_env_slippery_no_drop.yaml

wandb:
  init:
    entity: lagrassa
    project: mdes
    group: alex/validation
  saver:
    upload: True

skills:
  LiftAndDrop:
    low_level: False
    env: FrankaRodEnv # PushRodEnv, FrankaRodEnv
    data:
      mock: False
      #root: /home/jacky/plan_abstractions/skill_data/LQRWaypointsXYZYawFranka
      #val_root: /home/jacky/plan_abstractions/skill_data/LQRWaypointsXYZYawFranka
      root: /home/lagrassa/git/plan-abstractions/data/combined_data/
      val_root: /home/lagrassa/git/plan-abstractions/data/combined_data/
      val_tags:
        - LiftAndDrop_default__n_iter_0__seed_9
        - LiftAndDrop_default__n_iter_0__seed_6
        - RodInDrawerLiftAndDrop_datacollect__n_iter_0__seed_6
        - RodInDrawerLiftAndDrop_datacollect__n_iter_0__seed_0
        - RodInDrawerLiftAndDrop_default__n_iter_0__seed_7
        - LiftAndDrop_datacollect__n_iter_0__seed_4
        - LiftAndDrop_datacollect__n_iter_0__seed_5
      tags:
        - LiftAndDrop_default__n_iter_0__seed_3
        - LiftAndDrop_datacollect__n_iter_0__seed_1
        - RodInDrawerLiftAndDrop_datacollect__n_iter_0__seed_5
        - RodInDrawerLiftAndDrop_default__n_iter_0__seed_8
        - LiftAndDrop_datacollect__n_iter_0__seed_3
        - LiftAndDrop_default__n_iter_0__seed_4
        - LiftAndDrop_default__n_iter_0__seed_0 #fine
        - RodInDrawerLiftAndDrop_datacollect__n_iter_0__seed_7
        - LiftAndDrop_default__n_iter_0__seed_1
        - LiftAndDrop_default__n_iter_0__seed_8
        - LiftAndDrop_default__n_iter_0__seed_2
        - LiftAndDrop_default__n_iter_0__seed_7 #fine
        - LiftAndDrop_default__n_iter_0__seed_10 #fine
        - LiftAndDrop_default__n_iter_0__seed_11 #fine
        - LiftAndDrop_default__n_iter_0__seed_12 #fine
        - LiftAndDrop_default__n_iter_0__seed_13
        - LiftAndDrop_datacollect__n_iter_0__seed_0
        - LiftAndDrop_datacollect__n_iter_0__seed_2
        - LiftAndDrop_datacollect__n_iter_0__seed_6
        - RodInDrawerLiftAndDrop_default__n_iter_0__seed_0
        - RodInDrawerLiftAndDrop_default__n_iter_0__seed_1
        - RodInDrawerLiftAndDrop_default__n_iter_0__seed_2
        - RodInDrawerLiftAndDrop_default__n_iter_0__seed_3
        - RodInDrawerLiftAndDrop_default__n_iter_0__seed_4
        - RodInDrawerLiftAndDrop_default__n_iter_0__seed_5
        - RodInDrawerLiftAndDrop_default__n_iter_0__seed_6
        - RodInDrawerLiftAndDrop_datacollect__n_iter_0__seed_2
        - RodInDrawerLiftAndDrop_datacollect__n_iter_0__seed_3
        - RodInDrawerLiftAndDrop_datacollect__n_iter_0__seed_4
      sem_state_obj_names:
        - franka:ee
        - rod0
        - rod1
      normalization_type: 'z_normalization'    # 'none', 'z_normalization', 'min_max'? #TODO use same as dynamics model
      z_normalization:
        # mean_std per feature ()
        # can only normalize values we require also maybe try min-max?
        mean: [  0,  0,  0,  0,  0,  0,  0,  0,  0,0,0,0,  828.628,   3.886,   0.059]
        std:  [  1,  1,  1,  1,  1,  1,  1,  1,  1,1,1,1,   22.012,   3.440,   0.004]
      skill: LiftAndDrop # the skill class name
      state_info:
        use_state_diff_in_end_state: True
        # anchor_obj_name: pusher # uncomment to use relative states
    sem_cfg:
      type: SEMAnalyticalRodsAndRobot # SEMMLP
      env: FrankaRodEnv
      drawer_edge_dims : [0.25, 0.01, 0.07] #Make sure matches with URDF
      predict:
        num_samples: 1
        truncate: 0.1
      sem_state_obj_names:
        - franka:ee
        - rod0
        - rod1
      normalization_type: 'z_normalization'    # 'none', 'z_normalization', 'min_max'? #TODO use same as dynamics model
      z_normalization:
        # mean_std per feature ()
        # can only normalize values we require also maybe try min-max?
        mean: [  0,  0,  0,  0,  0,  0,  0,  0,  0,0,0,0,  828.628,   3.886,   0.059]
        std:  [  1,  1,  1,  1,  1,  1,  1,  1,  1,1,1,1,   22.012,   3.440,   0.004]
      skill: LiftAndDrop # the skill class name
      state_info:
        use_state_diff_in_end_state: True
        # anchor_obj_name: pusher # uncomment to use relative states

